#SPDX-License-Identifier: MIT-0
---
# tasks file for roles/launch-database

- name: Run database
  docker_container:
    env:
      POSTGRES_PASSWORD: pwd
    name: database
    image: francoisthievon/tp-devops-simple-api-database
    pull: yes
    networks: 
      - name: app-network