#SPDX-License-Identifier: MIT-0
---
# tasks file for roles/launch-app

- name: Run backend
  docker_container:
    env:
      DATABASE_HOST: database
      DATABASE_PASSWORD: pwd
    name: backend
    image: francoisthievon/tp-devops-simple-api-backend
    pull: yes
    networks: 
      - name: app-network
