#SPDX-License-Identifier: MIT-0
---
# tasks file for roles/launch-proxy

- name: Run HTTPD
  docker_container:
    name: httpd
    image: francoisthievon/tp-devops-simple-api-httpd
    networks: 
      - name: app-network
    ports:
      - "80:80"